name: Publish Package

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
      
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Bump version (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git add package.json package-lock.json
          git commit -m "chore: bump version to v$VERSION"
          git push
      
      - name: Bump patch version (auto)
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'chore:') == false
        run: |
          npm version patch --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git add package.json package-lock.json
          git commit -m "chore: bump version to v$VERSION [skip ci]"
          git push
      
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Release
        if: env.VERSION != ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: "v${{ env.VERSION }}"
          body: |
            ## What's Changed
            - Automated release of @mcoster/astro-local-package v${{ env.VERSION }}
            
            Full Changelog: https://github.com/${{ github.repository }}/commits/v${{ env.VERSION }}
          draft: false
          prerelease: false
      
      - name: Trigger dependent site updates
        if: env.VERSION != ''
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_TOKEN || secrets.GITHUB_TOKEN }}
          repository: mcoster/gold-coast-roof-cleaning-pros
          event-type: package-update
          client-payload: '{"package": "@mcoster/astro-local-package", "version": "${{ env.VERSION }}"}'